baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "pt-PT"

title: "NUAL"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "NUAL"
  description: Ajudamos os nossos clientes a reduzir custos, 
    aumentar a eficiência e garantir a segurança dos seus sistemas de bombagem.
  images: 
    - "images/digi_water.png"
    - "images/hero-bg.jpg"

  # config.toml
  logo: "images/nual_logo.png"


  favicons:
    themeColor: #94fa69
    backgroundColor: #94fa69
    faviconColor: #94fa69

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - Santo Tirso, Porto, Portugal

  contact: "info@nual.pt"

  copyright: "© 2024 NUAL All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Produtos"
      url: "/blog"
      weight: 2

  buttons:
    - name: "Contacte-nos"
      url: "/contact"
      weight: 3
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Sobre nós"
      url: "/contact"
      weight: 2

    - name: "Produtos"
      url: "/produtos"
      weight: 3

taxonomies:
  series: "series"
  tags: "tags"
